name: 'shop'
version: '1.0.0'

profile: 'shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  shop:
    staging:
      +materialized: view

seeds:
  shop:
    +enabled: true

    categories:
      +column_types:
        category_id: int
        name: varchar(50)
    
    statuses:
      +column_types:
        status_id: int
        name: varchar(50)

    units_of_measure:
      +column_types:
        uom_id: int
        name: varchar(50)
        short_name: varchar(10)

    products:
      +column_types:
        product_id: int
        name: varchar(255)
        category_id: int
        price: numeric(10, 2)
        updated_at: timestamp
        is_active: boolean